name: Nightly Smoke Tests

on:
  # Trigger manually or on schedule
  workflow_dispatch:
    inputs:
      verbose:
        description: 'Enable NX_VERBOSE_LOGGINNG'
        default: false
        required: false
  workflow_call:
  schedule:
    - cron: '0 0 * * *'

jobs:
  smoke:
    name: Nightly Smoke Test
    strategy:
      fail-fast: false
      matrix:
        dotnet_version: ['6.0.300', '7.0.x']
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    timeout-minutes: 30
    env:
      NX_RUN_GROUP: ${{ github.run_id }}-v${{matrix.dotnet_version}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{matrix.dotnet_version}}
          include-prerelease: true
      - uses: bahmutov/npm-install@v1
      - run: yarn nx run-many --all --target=smoke
        env:
          NX_VERBOSE_LOGGING: ${{ github.event.inputs.verbose }}
